# default config.yml

AutoUpdate: false

# Protection

MinimumZoneSize: 6

ProtectChests: true #If a player places a chest and has no protections, a new one is created around the chest

# Land

BuyableLand: true
StartLand: 500 # Width X Length ( 10 x 10 ) (Must be a square number)

LandGain: 175 #The amount you gain
LandDelay: 600 #The delay between each gain of land
SendMessage: true #Sends a message when they gain land

# Items

#Any items you don't want people to be able to use in other peoples protections outside of normal
#mining / placing (For example, a rod of protection from this plugin)
BlockedItems:
   - 2256
   - 2257
   - 2258
   - 2259
   - 2260
   - 2261
   - 2262
   - 2263
   - 2264
   - 2265
   - 2266
   - 2267
   - 351
   - 381
   - 385

# Block

RightClickIronDoor: true

FireBurn: false
FireSpread: false

# Players

PlayersTrampleCrops: false

PlayersCanCreatePortals: true

PreventPVPLog: false
PreventPVPTeleport: false

# Entity

EntitiesTrampleCrops: false

TNTDamageEntity: true
TNTBlockDamage: false

TNTCartDamageEntity: true
TNTCartBlockDamage: false

CreeperDamageEntity: true
CreeperBlockDamage: false

GhastDamageEntity: true
GhastBlockDamage: false

WitherDamageEntity: true
WitherBlockDamage: false

WitherHeadDamageEntity: true
WitherHeadBlockDamage: false

EnderCrystalDamageEntity: true
EnderCrystalBlockDamage: false

EndermenBlockChange: false

EnderDragonBlockDamage: false
ZombiesBreakDoors: false